name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/rentgaadi-backend:latest \
          .

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/rentgaadi-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/rentgaadi-backend:latest

              docker stop rentgaadi-backend || true
              docker rm rentgaadi-backend || true

              docker run -d \
                --name rentgaadi-backend \
                --restart unless-stopped \
                -p 5000:5000 \
                --env-file ~/.env \
                ${{ secrets.DOCKER_USERNAME }}/rentgaadi-backend:latest